apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: platform-api-kv
  namespace: platform
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "__WORKLOAD_CLIENT_ID__"
    keyvaultName: "__KEYVAULT_NAME__"
    tenantId: "__TENANT_ID__"
    objects: |
      array:
        - |
          objectName: PlatformApi--Greeting
          objectType: secret
